cargo-features = ["per-package-target"]

[package]
name = "key_value_lookup"
version = "0.1.0"
authors = ["Tiziano Santoro <tzn@google.com>"]
edition = "2021"
license = "Apache-2.0"
forced-target = "wasm32-unknown-unknown"

[lib]
crate-type = ["cdylib", "rlib"]
# We cannot execute tests with the forced-target wasm32-unknown-unknown.
test = false

[dependencies]
oak_functions = { path = "../../../sdk/oak_functions" }

[dev-dependencies]
oak_functions_loader = { path = "../../../loader" }
oak_functions_abi = { path = "../../../abi" }
http = "*"
hyper = { version = "*", features = ["client", "http2"] }
maplit = "*"
prost = "*"
test_utils = { path = "../../../sdk/test_utils" }
tokio = { version = "*", features = [
  "fs",
  "macros",
  "sync",
  "rt-multi-thread"
] }
