cargo-features = ["per-package-target"]

[package]
name = "benchmark"
version = "0.1.0"
authors = ["Conrad Grobler <grobler@google.com>"]
edition = "2021"
license = "Apache-2.0"
forced-target = "wasm32-unknown-unknown"

[lib]
crate-type = ["cdylib", "rlib"]
# We cannot execute tests with the forced-target wasm32-unknown-unknown.
test = false

[dependencies]
oak_functions = { path = "../../../sdk/oak_functions" }
prost = "*"

[build-dependencies]
prost-build = "*"
